//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.09 at 02:50:05 PM PDT 
//


package com.oracle.demo.ops.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oracle.demo.ops.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle.demo.ops.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateShipmentResponse }
     * 
     */
    public CreateShipmentResponse createCreateShipmentResponse() {
        return new CreateShipmentResponse();
    }

    /**
     * Create an instance of {@link GetShipmentByExternalIdRequest }
     * 
     */
    public GetShipmentByExternalIdRequest createGetShipmentByExternalIdRequest() {
        return new GetShipmentByExternalIdRequest();
    }

    /**
     * Create an instance of {@link CreateShipmentRequest }
     * 
     */
    public CreateShipmentRequest createCreateShipmentRequest() {
        return new CreateShipmentRequest();
    }

    /**
     * Create an instance of {@link GetParcelByIdRequest }
     * 
     */
    public GetParcelByIdRequest createGetParcelByIdRequest() {
        return new GetParcelByIdRequest();
    }

    /**
     * Create an instance of {@link Parcel }
     * 
     */
    public Parcel createParcel() {
        return new Parcel();
    }

    /**
     * Create an instance of {@link GetShipmentByExternalIdResponse }
     * 
     */
    public GetShipmentByExternalIdResponse createGetShipmentByExternalIdResponse() {
        return new GetShipmentByExternalIdResponse();
    }

    /**
     * Create an instance of {@link ShippingService }
     * 
     */
    public ShippingService createShippingService() {
        return new ShippingService();
    }

    /**
     * Create an instance of {@link GetShipmentByIdRequest }
     * 
     */
    public GetShipmentByIdRequest createGetShipmentByIdRequest() {
        return new GetShipmentByIdRequest();
    }

    /**
     * Create an instance of {@link GetParcelEventLogRequest }
     * 
     */
    public GetParcelEventLogRequest createGetParcelEventLogRequest() {
        return new GetParcelEventLogRequest();
    }

    /**
     * Create an instance of {@link GetParcelByIdResponse }
     * 
     */
    public GetParcelByIdResponse createGetParcelByIdResponse() {
        return new GetParcelByIdResponse();
    }

    /**
     * Create an instance of {@link PostalGeolocation }
     * 
     */
    public PostalGeolocation createPostalGeolocation() {
        return new PostalGeolocation();
    }

    /**
     * Create an instance of {@link Shipment }
     * 
     */
    public Shipment createShipment() {
        return new Shipment();
    }

    /**
     * Create an instance of {@link AddParcelEventJMSPROXYResponse }
     * 
     */
    public AddParcelEventJMSPROXYResponse createAddParcelEventJMSPROXYResponse() {
        return new AddParcelEventJMSPROXYResponse();
    }

    /**
     * Create an instance of {@link WebServiceResponseHeader }
     * 
     */
    public WebServiceResponseHeader createWebServiceResponseHeader() {
        return new WebServiceResponseHeader();
    }

    /**
     * Create an instance of {@link GetParcelEventLogResponse }
     * 
     */
    public GetParcelEventLogResponse createGetParcelEventLogResponse() {
        return new GetParcelEventLogResponse();
    }

    /**
     * Create an instance of {@link GetShipmentByIdResponse }
     * 
     */
    public GetShipmentByIdResponse createGetShipmentByIdResponse() {
        return new GetShipmentByIdResponse();
    }

    /**
     * Create an instance of {@link AddParcelEventJMSPROXYRequest }
     * 
     */
    public AddParcelEventJMSPROXYRequest createAddParcelEventJMSPROXYRequest() {
        return new AddParcelEventJMSPROXYRequest();
    }

    /**
     * Create an instance of {@link ParcelEvent }
     * 
     */
    public ParcelEvent createParcelEvent() {
        return new ParcelEvent();
    }

    /**
     * Create an instance of {@link SendNewShipmentViaJMSRequest }
     * 
     */
    public SendNewShipmentViaJMSRequest createSendNewShipmentViaJMSRequest() {
        return new SendNewShipmentViaJMSRequest();
    }

    /**
     * Create an instance of {@link SendNewShipmentViaJMSResponse }
     * 
     */
    public SendNewShipmentViaJMSResponse createSendNewShipmentViaJMSResponse() {
        return new SendNewShipmentViaJMSResponse();
    }

    /**
     * Create an instance of {@link WebServiceRequestHeader }
     * 
     */
    public WebServiceRequestHeader createWebServiceRequestHeader() {
        return new WebServiceRequestHeader();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

}
