//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.09 at 04:12:12 PM PDT 
//


package com.oracle.demo.ops.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShipmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://demo.oracle.com/ops/domain/schema/common}BaseEntity">
 *       &lt;sequence>
 *         &lt;element name="ExternalReferenceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ToAddress" type="{http://demo.oracle.com/ops/domain/schema/common}Address"/>
 *         &lt;element name="FromAddress" type="{http://demo.oracle.com/ops/domain/schema/common}Address"/>
 *         &lt;element name="ShippingServiceName" type="{http://demo.oracle.com/ops/domain/schema/shipping}ShippingServiceName"/>
 *         &lt;element ref="{http://demo.oracle.com/ops/domain/schema/shipping}Parcel" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentType", namespace = "http://demo.oracle.com/ops/domain/schema/shipping", propOrder = {
    "externalReferenceId",
    "toAddress",
    "fromAddress",
    "shippingServiceName",
    "parcels"
})
@XmlRootElement(name = "Shipment", namespace = "http://demo.oracle.com/ops/domain/schema/shipping")
public class Shipment
    extends BaseEntity
    implements Serializable
{

    private final static long serialVersionUID = 678L;
    @XmlElement(name = "ExternalReferenceId", required = true)
    protected String externalReferenceId;
    @XmlElement(name = "ToAddress", required = true)
    protected Address toAddress;
    @XmlElement(name = "FromAddress", required = true)
    protected Address fromAddress;
    @XmlElement(name = "ShippingServiceName", required = true)
    protected ShippingServiceName shippingServiceName;
    @XmlElement(name = "Parcel", required = true)
    protected List<Parcel> parcels;

    /**
     * Gets the value of the externalReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalReferenceId() {
        return externalReferenceId;
    }

    /**
     * Sets the value of the externalReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalReferenceId(String value) {
        this.externalReferenceId = value;
    }

    /**
     * Gets the value of the toAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getToAddress() {
        return toAddress;
    }

    /**
     * Sets the value of the toAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setToAddress(Address value) {
        this.toAddress = value;
    }

    /**
     * Gets the value of the fromAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getFromAddress() {
        return fromAddress;
    }

    /**
     * Sets the value of the fromAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setFromAddress(Address value) {
        this.fromAddress = value;
    }

    /**
     * Gets the value of the shippingServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingServiceName }
     *     
     */
    public ShippingServiceName getShippingServiceName() {
        return shippingServiceName;
    }

    /**
     * Sets the value of the shippingServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingServiceName }
     *     
     */
    public void setShippingServiceName(ShippingServiceName value) {
        this.shippingServiceName = value;
    }

    /**
     * Gets the value of the parcels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parcels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParcels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parcel }
     * 
     * 
     */
    public List<Parcel> getParcels() {
        if (parcels == null) {
            parcels = new ArrayList<Parcel>();
        }
        return this.parcels;
    }

}
